### PR TITLE
CB-10561: Removing wp8 and windows-store-8.0 builders

### PR DESCRIPTION
**Pull request by rakatyal**
wp8 is deprecated and windows8 is not used anymore

### CODE REVIEW

**Comment by omefire** [comment]
Do we need to remove this ?
https://github.com/apache/cordova-medic/pull/75/files#diff-02ebb0a2743750f76789021349d1f4c9R207

**Comment by omefire** [comment]
... and this ?
https://github.com/apache/cordova-medic/pull/75/files#diff-02ebb0a2743750f76789021349d1f4c9R221

**Comment by rakatyal** [comment]
Yes. I missed to git add that file. Updated.

**Comment by dblotsky** [comment]
LGTM. @rakatyal do you want to try to follow the SVN commit process? If you do, perform the SVN part before the git part.

**Comment by omefire** [comment]
LGTM!

**Pull request merged**
