### PR TITLE
CB-10401: Connectivity Issue to github from cordova-

### PR DESCRIPTION
**Pull request by sarangan12**
Adding retry logic to cloning github repositories. Added 2 parameters:
1. retryFetch - Git specific parameter - Ref Link:
http://docs.buildbot.net/0.8.9/manual/cfg-buildsteps.html#git
2. retry - Common parameter -
http://docs.buildbot.net/0.8.9/manual/cfg-buildsteps.html#id3

Logic is to retry 3 times with a 10 second delay.

### CODE REVIEW

**Comment by sarangan12** [comment]
@dblotsky @nikhilkh @riknoll @alsorokin Can you please review and merge this PR? Tks.

**Comment by dblotsky** [comment]
LGTM!

**Comment by nikhilkh** [comment]
@dblotsky Are you planning to commit this to svn repo?

**Comment by dblotsky** [comment]
@nikhilkh: yep. Committed at the same time that this got merged.

**Pull request merged**
