### PR TITLE
CB-9660 Kill wp8.1 emulator in medic-kill on Windows

### PR DESCRIPTION
**Pull request by alsorokin**
https://issues.apache.org/jira/browse/CB-9660

### CODE REVIEW

**Comment by dblotsky** [comment]
Just a thought: are WP8 and WP8.1 emulators using the same process?

**Comment by alsorokin** [comment]
@dblotsky yep, same process.
I agree that this could be a problem if we need to debug a windows phone 8.1 build and it is followed by wp8 build which kills the wp81 emulator or vice versa, but I think there is nothing we can do about it.

**Comment by dblotsky** [comment]
In the future we can probably do something like inspect the running processes, find the specific one we want to kill, and then kill it by PID.

**Comment by dblotsky** [comment]
LGTM though.

**Pull request closed without merging**
