### PR TITLE
CB-11237: linking cordova-fetch

### PR DESCRIPTION
**Pull request by riknoll**
See [CB-11237](https://issues.apache.org/jira/browse/CB-11237). I have not tested this code, because I do not have a buildbot dev environment set up.

### CODE REVIEW

**Comment by riknoll** [comment]
@rakatyal @stevengill please review

**Comment by rakatyal** [comment]
LGTM.

**Comment by stevengill** [comment]
LGTM too! Sorry I forgot about medic :(

**Comment by riknoll** [comment]
@stevengill no worries! Thanks for taking a look!

**Pull request merged**
